// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetLpr.Persistence.Sqlite;

#nullable disable

namespace NetLpr.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20261002143745_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("NetLpr.Persistence.Sqlite.Models.RtspSourceInfoDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnalysesOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathAndQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("RoiHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("RoiWidth")
                        .HasColumnType("REAL");

                    b.Property<float>("RoiX")
                        .HasColumnType("REAL");

                    b.Property<float>("RoiY")
                        .HasColumnType("REAL");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RtspSources", (string)null);
                });

            modelBuilder.Entity("NetLpr.Persistence.Sqlite.Models.StreamAnalysesAreaPointDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("StreamAnalysesAreaPoints", (string)null);
                });

            modelBuilder.Entity("NetLpr.Persistence.Sqlite.Models.TrackedInfoDbModel", b =>
                {
                    b.Property<string>("TrackedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateRectangle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrackedId");

                    b.ToTable("TrackedInfos", (string)null);
                });

            modelBuilder.Entity("NetLpr.Persistence.Sqlite.Models.StreamAnalysesAreaPointDbModel", b =>
                {
                    b.HasOne("NetLpr.Persistence.Sqlite.Models.RtspSourceInfoDbModel", null)
                        .WithMany("AnalysesArea")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetLpr.Persistence.Sqlite.Models.RtspSourceInfoDbModel", b =>
                {
                    b.Navigation("AnalysesArea");
                });
#pragma warning restore 612, 618
        }
    }
}
