<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Assets\Icons.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetLpr.Core\NetLpr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\Icons.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\TrackedInfoResultView.axaml.cs">
      <DependentUpon>TrackedInfoResultView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SettingsView.axaml.cs">
      <DependentUpon>SettingsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CameraEditView.axaml.cs">
      <DependentUpon>CameraEditView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
